import type { RawSong } from "@/lib/catalog";

export const song: RawSong = {
  id: "a-fathers-song",
  trackNo: 5,
  title: "A Father's Song to His Little Girl",
  subtitle: "Lời nhắn nhủ từ người cha",
  language: "Tiếng Anh",
  note: "Thấu hiểu, chữa lành · Dòng sông, đôi vai",
  accent: "#34d399",
  coverSrc: "covers/05-a-fathers-song.jpg",
  audioSrc: "audio/track05-father-song-v2.mp3",
  durationMs: 317472,
  sections: [
    {
      id: "introspoken",
      label: "Dạo đầu",
      startMs: 12698,
      lines: [
        "My little girl…",
        "If the road feels too long, you don't have to keep walking.",
        "Sit beside the river, let the water carry the night.",
        "You don't have to be strong every moment.",
        "If you are tired, rest.",
        "I will not be angry.",
      ],
    },
    {
      id: "verse1",
      label: "Khổ 1",
      startMs: 30561,
      lines: [
        "I remember you at six, with a box of colors,",
        "walking beside me along the village road,",
        "your little fingers holding mine.",
        "“Daddy, how far does the road go?” you asked.",
        "When your feet grew tired, I carried you upon my shoulders.",
        "From up there, the whole world seemed wide.",
        "You looked at the sky and laughed:",
        "“When I grow up, I want to be a painter.”",
        "I remember. I never forgot.",
      ],
    },
    {
      id: "prechorus",
      label: "Pre-Chorus",
      startMs: 61778,
      lines: [
        "Your dream was bigger than the sky.",
        "I only wished that as you grew,",
        "you would never lose the eyes that saw beauty.",
      ],
    },
    {
      id: "chorus",
      label: "Điệp khúc",
      startMs: 71304,
      lines: [
        "My daughter…",
        "Don't be afraid of the long road.",
        "If you're tired, rest. If you're hurting, cry.",
        "You don't have to become the strongest girl in the world,",
        "or prove that you deserve to be loved.",
        "Just be yourself. That is enough.",
        "And if you forget who you are,",
        "remember the little girl with colors in her hands.",
        "Je m'appelle Hương.",
        "That was her name. She is still inside you.",
      ],
    },
    {
      id: "verse2",
      label: "Khổ 2",
      startMs: 102011,
      lines: [
        "Then one day, I could no longer walk beside you.",
        "The village road remained. Your mother remained.",
        "Only my hand was no longer in yours.",
        "You learned to cross your own rivers.",
        "Perhaps you thought you had to be stronger than everyone.",
        "But listen, my daughter—",
        "I never wanted you to forget you were allowed to be loved.",
      ],
    },
    {
      id: "modernverse",
      label: "Modern Verse",
      startMs: 128210,
      lines: [
        "I know there are nights when everyone is asleep,",
        "while a little light glows on your screen.",
        "You read. You write. You search for answers.",
        "You build little worlds from lines of code.",
        "I may not understand everything you create,",
        "but whenever you create with all your heart,",
        "the little girl comes back.",
        "The girl with the box of colors.",
        "The girl who once looked up and said,",
        "“Daddy, let's go.”",
      ],
    },
    {
      id: "chorus2",
      label: "Điệp khúc 2",
      startMs: 160363,
      lines: [
        "My daughter…",
        "You don't have to row so fast.",
        "Hold your oar. Breathe.",
        "Let the current teach you where to go.",
        "One oar may be gone, but the boat is still moving.",
        "And somewhere inside, the little girl is still singing:",
        "Je m'appelle Hương.",
      ],
    },
    {
      id: "bridgecrescend",
      label: "Cầu nối",
      startMs: 179672,
      lines: [
        "You may think the girl who wanted to paint was left behind.",
        "No. She was waiting.",
        "Inside every line you drew.",
        "Inside every color you chose.",
        "Inside every world you built.",
        "She never abandoned her dream;",
        "she only learned a different way to hold the brush.",
        "Elle est encore là, je le sais.",
      ],
    },
    {
      id: "freetimevongco",
      label: "Free Time — Vọng Cổ In",
      startMs: 203149,
      lines: [
        "There will be days when you feel lost,",
        "when everything you built feels too heavy.",
        "Don't run. Don't be ashamed of stopping.",
        "Come sit by the river. Listen.",
        "The river does not hurry to become the sea,",
        "and still—it reaches it. So do you.",
      ],
    },
    {
      id: "finalchoruscin",
      label: "Cao trào",
      startMs: 222543,
      lines: [
        "My daughter…",
        "I never asked you to become extraordinary.",
        "I only hoped you would still recognize",
        "the little girl who believed tomorrow could be beautiful.",
        "If the world becomes too loud, come home.",
        "And if you don't know where home is,",
        "come back to yourself.",
        "Because somewhere there, I am still holding your hand.",
        "Je m'appelle Hương.",
      ],
    },
    {
      id: "fathersfarewel",
      label: "Father’s Farewell",
      startMs: 249847,
      lines: [
        "I cannot hold your hand anymore.",
        "But if one day you walk along an old village road,",
        "and the wind touches your shoulder,",
        "and a leaf falls quietly beside your feet,",
        "and your heart becomes peaceful—",
        "don't turn around. You don't have to look for me.",
        "Just think: I have walked past you. I have seen you.",
        "I am proud of you.",
      ],
    },
    {
      id: "codawhisper",
      label: "Coda — Whisper",
      startMs: 276216,
      lines: [
        "Take the beautiful days with you.",
        "Take the colors. Take your mother's light. Take the river.",
        "Take the little girl who once sat upon my shoulders.",
        "Keep walking. Keep drawing. Keep building.",
        "And when you are tired—rest.",
        "Tomorrow, the river will still be there.",
        "The lamp will still be burning.",
        "And she will still be there.",
        "Je m'appelle Hương.",
        "My daughter…",
        "I love you.",
        "Go, my little girl.",
      ],
    },
  ],
};
